name: Build PR (Manual)
on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "zulu"

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-build-outputs: true

      - name: Build Debug APK
        run: ./gradlew assembleFossDebug --build-cache --stacktrace
        env:
          PULL_REQUEST: 'true'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/foss/debug/*.apk